# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 1,   size: 0.16},
    {id: 3,   size: 0.2},
    {id: 18,   size: 0.16},
    {id: 34,   size: 0.16},
    {id: 88,   size: 0.16},
    {id: 131,   size: 0.16},
    {id: 152,   size: 0.16},
    {id: 177,   size: 0.44},
    {id: 199,   size: 0.16},
    {id: 270,   size: 0.16},
    {id: 355,   size: 0.16}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
   [
    #  {
    #    name: 'tag_bundle1',
    #    layout:
    #      [
    #        # for a pixel = ~8mm
    #        {id: 1,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 18,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 34,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 88,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 131,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 152,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 199,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 270,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0},
    #        {id: 355,   size: 0.16, x: 0.0000, y:  0.0000, z: 0, qw: 1, qx: 0, qy: 0, qz: 0}
    #      ]
    #  },
   ]
